### ISSUE TITLE
Hide commandline when verbosity: 'quiet'

### ISSUE THREAD

**Issue by srijken** [mikeobrien/node-nuget-runner#3]
When running with `verbosity: 'quiet'`, the nuget commandline is still output, see:

https://github.com/mikeobrien/node-nuget-runner/blob/master/src/process.js#L12-L14

it would be nice if it were possible to hide this as well. Not sure if it should be hooked up to 'quiet', or some other flag to turn it off.

**Comment by mikeobrien** [comment]
Yeah, that flag is simply passed on as an argument to nuget, doesn't actually control anything in the package as you noted. Not something I'm interested in adding myself but would definitely accept a PR.
